"""GF(2^8) in both stacks, against an independent implementation of the field.

Why this exists
---------------
Every assertion the repository made about this field was self-referential:
``a * a^-1 == 1``, ``gfDiv(gfMul(a, b), b) == a``, encode-then-decode round-trips.
All of them hold in *any* correctly built GF(2^8), not only in the one SPEC.md
specifies. Measured before this suite was written: changing ``POLY`` from 0x11D
to 0x12D, which is also primitive with generator 2, left all 620 tests of the
TypeScript suite green while changing 96% of the parity bytes on a k=4, m=3 shard
set (50% at k=1, m=2; 99.7% at k=10, m=3).

The Python conformance suite does not close it either, and the way it appears to
is worth recording. Against fixtures left over from a previous field it fails four
tests, which reads like a catch. It is not: ``python/tests/_fixtures/`` is
gitignored and regenerated by the TypeScript encoder on every run, so CI never
holds a stale fixture. Regenerated the way CI regenerates them, all 89 of its
tests pass under the wrong field.

So the two stacks cannot catch this between them. They were written from one
specification by similar means, so they can share a misreading of it, which is the
same argument that put ``tests/compliance`` in the repository for AEAD.

The two oracles
---------------
``reedsolo`` is a second independent implementation whose defaults are this exact
field (``prim=0x11d, generator=2``). Useful, but only a second opinion: it has no
standardised vectors behind it, unlike the NIST CAVP sets crypto-condor drives.

``reedsolo.gf_mult_noLUT`` is the one that carries the argument. It is a
Russian-peasant carry-less multiply with modular reduction and **no tables at
all**, so comparing against it compares our table against the definition of the
field rather than against somebody else's table. If both were wrong in the same
way, they would have to be wrong in two unrelated algorithms.

What a fixed vector can and cannot pin
--------------------------------------
``POLY`` is fully observable: change it and products change. ``GENERATOR`` is not.
Any of this field's 128 primitive elements produces *identical* products, because
``log_g(xy) = log_g(x) + log_g(y)`` whatever the base g. What a different
generator changes is the exp/log tables, so ``test_exp_log_tables_match`` is the
only assertion here that pins it, and it is the reason that test exists as
something separate from the product sweep.

That is not a defect. Nothing in the format depends on the base: the Cauchy
matrix uses multiplication, division and inversion only. A different primitive
generator would produce a byte-identical output stream. It is written down so
that nobody later moves the generator assertion into the product test and
believes it still covers something.
"""

from __future__ import annotations

from typing import Any, Callable

import pytest

from conftest import EXPECTED_GENERATOR, EXPECTED_POLY

#: How many disagreements to name before truncating. A field that is wrong is
#: usually wrong in tens of thousands of places, and a failure message that
#: printed all of them would bury the count that matters.
MAX_REPORTED = 8

#: Sizes of the sweeps, asserted rather than assumed. Same reasoning as
#: tests/compliance/test_hash_hmac.py: a suite that quietly stopped covering the
#: whole field would still report green, and the dangerous drift is downward.
PRODUCTS = 256 * 256
QUOTIENTS = 256 * 255
INVERSES = 255

MulFn = Callable[[int, int], int]


def _report(kind: str, bad: list[str], total: int) -> None:
    if not bad:
        return
    shown = ", ".join(bad[:MAX_REPORTED])
    more = f", and {len(bad) - MAX_REPORTED} more" if len(bad) > MAX_REPORTED else ""
    pytest.fail(
        f"{kind}: {len(bad)} of {total} disagree with the reference field "
        f"(0x{EXPECTED_POLY:X}, generator 0x{EXPECTED_GENERATOR:02X}): {shown}{more}. "
        "This is not a tuning knob: the field decides every byte the erasure coder "
        "emits, and a change here breaks compatibility with every artifact already "
        "produced. Fix the implementation rather than this test."
    )


def check_products(label: str, mul: MulFn, rs: Any) -> None:
    """All 65,536 products, against the table implementation and the table-free one."""
    bad_tab: list[str] = []
    bad_raw: list[str] = []
    for a in range(256):
        for b in range(256):
            got = mul(a, b)
            if got != rs.gf_mul(a, b):
                bad_tab.append(f"{a:#04x}*{b:#04x}={got:#04x}")
            if got != rs.gf_mult_noLUT(a, b, EXPECTED_POLY, 256):
                bad_raw.append(f"{a:#04x}*{b:#04x}={got:#04x}")
    _report(f"{label} multiplication vs reedsolo", bad_tab, PRODUCTS)
    _report(f"{label} multiplication vs table-free reference", bad_raw, PRODUCTS)


def check_quotients(label: str, div: Callable[[int, int], int], rs: Any) -> None:
    """All 65,280 quotients with a non-zero divisor."""
    bad = [
        f"{a:#04x}/{b:#04x}={div(a, b):#04x}"
        for a in range(256)
        for b in range(1, 256)
        if div(a, b) != rs.gf_div(a, b)
    ]
    _report(f"{label} division vs reedsolo", bad, QUOTIENTS)


def check_inverses(label: str, inv: Callable[[int], int], rs: Any) -> None:
    """All 255 inverses. Zero is excluded: it has none, and reedsolo's
    ``gf_inverse`` would index ``gf_log[0]`` and return a number anyway rather
    than raising. Comparing there would manufacture a disagreement that says
    nothing about either implementation."""
    bad = [f"{a:#04x}^-1={inv(a):#04x}" for a in range(1, 256) if inv(a) != rs.gf_inverse(a)]
    _report(f"{label} inverses vs reedsolo", bad, INVERSES)


def check_tables(label: str, exp: list[int], log: list[int], rs: Any) -> None:
    """exp/log entry by entry. The only assertion here that pins GENERATOR."""
    bad_e = [f"exp[{i}]={exp[i]:#04x}" for i in range(255) if exp[i] != rs.gf_exp[i]]
    _report(f"{label} exp table vs reedsolo", bad_e, 255)
    # log[0] is skipped on both sides: it is never a valid input, gf256.ts never
    # writes it, and reedsolo never reads it.
    bad_l = [f"log[{i}]={log[i]}" for i in range(1, 256) if log[i] != rs.gf_log[i]]
    _report(f"{label} log table vs reedsolo", bad_l, 255)


# --------------------------------------------------------------------------
# The Python stack
# --------------------------------------------------------------------------


@pytest.fixture(scope="module")
def py_field() -> Any:
    from stegoshard import gf256

    return gf256


def test_python_field_parameters(py_field: Any) -> None:
    assert py_field.POLY == EXPECTED_POLY, (
        f"python reducing polynomial is {py_field.POLY:#x}, expected {EXPECTED_POLY:#x} "
        "(SPEC.md §7.1)"
    )
    assert py_field.GENERATOR == EXPECTED_GENERATOR


def test_python_products_match(py_field: Any, reedsolo_field: Any) -> None:
    check_products("python", py_field.gf_mul, reedsolo_field)


def test_python_quotients_match(py_field: Any, reedsolo_field: Any) -> None:
    check_quotients("python", py_field.gf_div, reedsolo_field)


def test_python_inverses_match(py_field: Any, reedsolo_field: Any) -> None:
    check_inverses("python", py_field.gf_inv, reedsolo_field)


def test_python_exp_log_tables_match(py_field: Any, reedsolo_field: Any) -> None:
    # Rebuilt through the public multiply rather than read from the module's own
    # table, so what is compared is what callers see.
    exp, log = [0] * 255, [0] * 256
    x = 1
    for i in range(255):
        exp[i] = x
        log[x] = i
        x = py_field.gf_mul(x, EXPECTED_GENERATOR)
    check_tables("python", exp, log, reedsolo_field)


# --------------------------------------------------------------------------
# The TypeScript stack
# --------------------------------------------------------------------------


def test_typescript_field_parameters(ts_field: dict[str, Any]) -> None:
    assert ts_field["poly"] == EXPECTED_POLY, (
        f"typescript reducing polynomial is {ts_field['poly']:#x}, expected "
        f"{EXPECTED_POLY:#x} (SPEC.md §7.1)"
    )
    assert ts_field["generator"] == EXPECTED_GENERATOR


def test_typescript_dump_is_complete(ts_field: dict[str, Any]) -> None:
    """The dump has to cover the whole field before its silence means anything.

    A truncated dump would make every sweep below pass over whatever it happened
    to contain, which is the shape of green this suite exists to refuse.
    """
    assert len(bytes.fromhex(ts_field["mul"])) == PRODUCTS
    assert len(bytes.fromhex(ts_field["div"])) == QUOTIENTS
    assert len(bytes.fromhex(ts_field["inv"])) == INVERSES
    assert len(bytes.fromhex(ts_field["exp"])) == 255
    assert len(bytes.fromhex(ts_field["log"])) == 256


def test_typescript_products_match(ts_field: dict[str, Any], reedsolo_field: Any) -> None:
    mul = bytes.fromhex(ts_field["mul"])
    check_products("typescript", lambda a, b: mul[a * 256 + b], reedsolo_field)


def test_typescript_quotients_match(ts_field: dict[str, Any], reedsolo_field: Any) -> None:
    div = bytes.fromhex(ts_field["div"])
    check_quotients("typescript", lambda a, b: div[a * 255 + (b - 1)], reedsolo_field)


def test_typescript_inverses_match(ts_field: dict[str, Any], reedsolo_field: Any) -> None:
    inv = bytes.fromhex(ts_field["inv"])
    check_inverses("typescript", lambda a: inv[a - 1], reedsolo_field)


def test_typescript_exp_log_tables_match(ts_field: dict[str, Any], reedsolo_field: Any) -> None:
    check_tables(
        "typescript",
        list(bytes.fromhex(ts_field["exp"])),
        list(bytes.fromhex(ts_field["log"])),
        reedsolo_field,
    )


# --------------------------------------------------------------------------
# The two stacks against each other
# --------------------------------------------------------------------------


def test_both_stacks_agree(py_field: Any, ts_field: dict[str, Any]) -> None:
    """Cheap, and it separates two failures that want different reactions.

    If this passes while the sweeps above fail, both stacks drifted together and
    the specification is what to check. If this fails, one of them drifted and the
    other is the reference.
    """
    mul = bytes.fromhex(ts_field["mul"])
    bad = [
        f"{a:#04x}*{b:#04x}: py={py_field.gf_mul(a, b):#04x} ts={mul[a * 256 + b]:#04x}"
        for a in range(256)
        for b in range(256)
        if py_field.gf_mul(a, b) != mul[a * 256 + b]
    ]
    _report("python vs typescript", bad, PRODUCTS)


# --------------------------------------------------------------------------
# The committed vectors
# --------------------------------------------------------------------------


def test_frozen_vectors_match_the_reference_field(reedsolo_field: Any) -> None:
    """The vector file has to be checked against something other than its author.

    ``tests/vectors/crypto-vectors.json`` was generated by the TypeScript stack,
    so vitest and pytest reproducing it proves the two stacks agree - the same
    thing they already agreed on before. Without this test the numbers would be a
    frozen snapshot of our own output, which is exactly the kind of self-reference
    this suite was built to break.
    """
    import json

    from conftest import REPO_ROOT

    gf = json.loads(
        (REPO_ROOT / "tests" / "vectors" / "crypto-vectors.json").read_text(encoding="utf-8")
    )["gf256"]

    assert gf["poly"] == EXPECTED_POLY
    assert gf["generator"] == EXPECTED_GENERATOR

    bad: list[str] = []
    for v in gf["products"]:
        # Both arms, so a vector cannot be blessed by the tabled path alone.
        for ref in (
            reedsolo_field.gf_mul(v["a"], v["b"]),
            reedsolo_field.gf_mult_noLUT(v["a"], v["b"], EXPECTED_POLY, 256),
        ):
            if v["product"] != ref:
                bad.append(f"{v['a']:#04x}*{v['b']:#04x}: frozen {v['product']:#04x} vs {ref:#04x}")
    for v in gf["quotients"]:
        ref = reedsolo_field.gf_div(v["a"], v["b"])
        if v["quotient"] != ref:
            bad.append(f"{v['a']:#04x}/{v['b']:#04x}: frozen {v['quotient']:#04x} vs {ref:#04x}")
    for v in gf["inverses"]:
        ref = reedsolo_field.gf_inverse(v["a"])
        if v["inverse"] != ref:
            bad.append(f"{v['a']:#04x}^-1: frozen {v['inverse']:#04x} vs {ref:#04x}")
    assert not bad, "frozen vectors disagree with the reference field: " + ", ".join(bad)


def test_frozen_vectors_would_not_survive_the_aes_field(reedsolo_field: Any) -> None:
    """The vectors must actually discriminate, not merely be reproducible.

    A vector set drawn from products that never overflow eight bits is identical
    in every GF(2^8) and pins nothing. This checks the committed pairs really do
    separate this field from the one they are most likely to be confused with.
    """
    import json

    from conftest import REPO_ROOT

    products = json.loads(
        (REPO_ROOT / "tests" / "vectors" / "crypto-vectors.json").read_text(encoding="utf-8")
    )["gf256"]["products"]

    differing = sum(
        1
        for v in products
        if v["product"] != reedsolo_field.gf_mult_noLUT(v["a"], v["b"], 0x11B, 256)
    )
    print(f"\n  {differing} of {len(products)} frozen products differ under the AES field 0x11B")
    assert differing == len(products), (
        f"only {differing} of {len(products)} committed products distinguish 0x11D from "
        "0x11B. A product that agrees across fields is decoration; replace it with one "
        "that reduces."
    )
