/**
 * Baseline JPEG coefficient codec: decode → coefficients → encode must be a
 * faithful round-trip (re-decoding yields identical coefficients), and the
 * non-baseline / malformed cases must be rejected rather than mis-parsed.
 */

import { describe, it, expect } from 'vitest';
import jpeg from 'jpeg-js';
import { JpegUnsupportedError, decode, encode, eligibleCoefficients, isJpeg } from './jpeg-coeff';

/** A deterministic baseline JPEG (jpeg-js emits 4:4:4 baseline Huffman). */
function makeJpeg(width: number, height: number, quality = 80, seed = 1): Uint8Array {
  const data = Buffer.alloc(width * height * 4);
  let s = seed >>> 0;
  for (let i = 0; i < width * height; i++) {
    s = (s * 1664525 + 1013904223) >>> 0;
    data[i * 4] = (i * 9) & 0xff;
    data[i * 4 + 1] = (i * 5) & 0xff;
    data[i * 4 + 2] = (s >>> 24) & 0xff;
    data[i * 4 + 3] = 255;
  }
  return new Uint8Array(jpeg.encode({ data, width, height }, quality).data);
}

function allCoeffs(model: ReturnType<typeof decode>): number[] {
  const out: number[] = [];
  for (const c of model.components) for (const b of c.blocks) out.push(...b);
  return out;
}

describe('baseline JPEG coefficient codec', () => {
  it('decodes then re-encodes to an equivalent baseline JPEG (coefficient identity)', () => {
    const jpg = makeJpeg(64, 48, 85, 7);
    const m1 = allCoeffs(decode(jpg));
    const reencoded = encode(decode(jpg));
    const m2 = allCoeffs(decode(reencoded));
    expect(m2).toEqual(m1); // re-decoding our output yields identical coefficients
    // Non-scan segments are preserved verbatim; size stays close.
    expect(Math.abs(reencoded.length - jpg.length)).toBeLessThan(64);
  });

  it('stays valid: jpeg-js can still decode our re-encoded output to pixels', () => {
    const jpg = makeJpeg(32, 32, 75, 3);
    const reencoded = encode(decode(jpg));
    const px = jpeg.decode(reencoded, { useTArray: true });
    expect(px.width).toBe(32);
    expect(px.height).toBe(32);
  });

  it('round-trips across quality levels and sizes', () => {
    for (const [w, h, q] of [
      [16, 16, 50],
      [40, 24, 92],
      [80, 80, 70],
    ] as const) {
      const jpg = makeJpeg(w, h, q, w + h + q);
      const before = allCoeffs(decode(jpg));
      const after = allCoeffs(decode(encode(decode(jpg))));
      expect(after).toEqual(before);
    }
  });

  it('exposes eligible AC coefficients (|coef| ≥ 2) and edits only their magnitude LSB', () => {
    const model = decode(makeJpeg(64, 64, 88, 11));
    const elig = eligibleCoefficients(model);
    expect(elig.count).toBeGreaterThan(736); // enough carriers for a key block
    // Flipping the LSB keeps |coef| ≥ 2 (same Huffman size category).
    const before = elig.get(0);
    elig.setLsb(0, before ^ 1);
    expect(elig.get(0)).toBe(before ^ 1);
  });

  it('rejects progressive JPEG', () => {
    // Hand-craft a minimal header with SOF2 (progressive) after SOI.
    const b = new Uint8Array([0xff, 0xd8, 0xff, 0xc2, 0x00, 0x02]);
    expect(() => decode(b)).toThrow(JpegUnsupportedError);
  });

  it('rejects non-JPEG bytes', () => {
    expect(isJpeg(new Uint8Array([0x89, 0x50]))).toBe(false);
    expect(() => decode(new Uint8Array([0x89, 0x50, 0x4e, 0x47]))).toThrow(JpegUnsupportedError);
  });
});

/**
 * Every structural refusal in the decoder, because this parser reads a file the
 * user was handed.
 *
 * Only two of these were covered before (progressive SOF2, and bytes that are
 * not a JPEG at all), and the branch coverage of jpeg-coeff.ts was the second
 * lowest in `src/core`. Each case here is built by hand from the marker up: a
 * fixture generated by an encoder cannot be malformed in the specific way each
 * guard exists to catch.
 *
 * The zero-dimension case is not hypothetical. The parser fuzzer found the
 * decoder accepting `8x0` and returning a model with no MCUs at all, so the
 * stego layer would have reported zero capacity on the file rather than refusing
 * it. That guard is new; this pins it.
 */
describe('jpeg decoder: structural refusals', () => {
  /** SOI, then one segment: marker, 2-byte length, body. */
  const seg = (marker: number, body: number[]) =>
    new Uint8Array([
      0xff,
      0xd8,
      0xff,
      marker,
      ((body.length + 2) >> 8) & 0xff,
      (body.length + 2) & 0xff,
      ...body,
    ]);

  /** A well-formed baseline SOF0 body: precision, h, w, nf, then one component. */
  const sof0 = (w: number, h: number, nf = 1) => [
    8,
    (h >> 8) & 0xff,
    h & 0xff,
    (w >> 8) & 0xff,
    w & 0xff,
    nf,
    ...Array.from({ length: nf }, (_, i) => [i + 1, 0x11, 0]).flat(),
  ];

  it('refuses arithmetic coding', () => {
    // 0xc9 is SOF9, arithmetic. Supported by the standard, not by this decoder,
    // and it must say so rather than misparse the scan as Huffman.
    expect(() => decode(seg(0xc9, [0]))).toThrow(JpegUnsupportedError);
  });

  it('refuses a sample precision other than 8 bits', () => {
    expect(() => decode(seg(0xc0, [12, 0, 8, 0, 8, 1, 1, 0x11, 0]))).toThrow(JpegUnsupportedError);
  });

  it('refuses a zero width or height', () => {
    // Legal in JPEG only with a DNL marker supplying the real height later,
    // which this decoder does not implement. Found by the fuzzer.
    expect(() => decode(seg(0xc0, sof0(8, 0)))).toThrow(JpegUnsupportedError);
    expect(() => decode(seg(0xc0, sof0(0, 8)))).toThrow(JpegUnsupportedError);
  });

  it('refuses a scan before any frame', () => {
    // SOS with no SOF: there is no component table to resolve the scan against.
    expect(() => decode(seg(0xda, [1, 1, 0x00, 0, 63, 0]))).toThrow(JpegUnsupportedError);
  });

  it('refuses a scan naming a component the frame never declared', () => {
    const frame = [...seg(0xc0, sof0(8, 8))];
    // Component id 9 was never declared by the SOF above.
    const sos = [0xff, 0xda, 0x00, 0x08, 1, 9, 0x00, 0, 63, 0];
    expect(() => decode(new Uint8Array([...frame, ...sos]))).toThrow(JpegUnsupportedError);
  });

  it('refuses a file that never reaches a scan', () => {
    // A valid frame and nothing after it. Silently returning a model with no
    // coefficients would look to the stego layer like an empty carrier.
    expect(() => decode(seg(0xc0, sof0(8, 8)))).toThrow(JpegUnsupportedError);
  });

  it('refuses a byte where a marker must be', () => {
    // Desynchronised segment walk: the length field of the first segment lies,
    // so the parser lands mid-data instead of on 0xff.
    const b = new Uint8Array([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x20, ...new Array(10).fill(0x41)]);
    expect(() => decode(b)).toThrow(JpegUnsupportedError);
  });

  it('refuses a scan whose Huffman codes are not in the tables', () => {
    // A frame and a scan, but no DHT at all, so the first symbol has nowhere to
    // resolve. This is also the shape a truncated file arrives in.
    const frame = [...seg(0xc0, sof0(8, 8))];
    const sos = [0xff, 0xda, 0x00, 0x08, 1, 1, 0x00, 0, 63, 0, 0x55, 0x55, 0xff, 0xd9];
    expect(() => decode(new Uint8Array([...frame, ...sos]))).toThrow(JpegUnsupportedError);
  });
});

describe('jpeg decoder: truncation', () => {
  /**
   * A truncated scan is refused, and this pins that it already was.
   *
   * Past the end of the entropy data the bit reader feeds 1-bits, the JPEG pad
   * convention. Unbounded, that reads like a hole: a short file could be fed
   * synthetic bits until the decoder manufactured a full set of coefficients,
   * and the stego layer would then read a key block out of fabricated data.
   *
   * A bound was written for exactly that, then removed, because measuring it
   * showed it never fired. Over 712 truncation points across three files,
   * limiting the padding to two bytes changed the outcome in **zero** cases. The
   * Huffman decoder already refuses a short scan, since synthetic 1-bits do not
   * resolve to valid codes; the only truncations that decode are the last two or
   * three bytes, which is the padding the convention describes.
   *
   * So this suite records a property the decoder has rather than one that had to
   * be added. Worth keeping precisely because it was nearly a guard nobody would
   * have noticed was dead.
   */
  it('refuses a scan cut short instead of fabricating coefficients', () => {
    const full = makeJpeg(64, 64, 88, 11);
    let refused = 0;
    let decoded = 0;
    // Cut at several depths: near the end, mid-scan, and early.
    for (const keep of [0.98, 0.9, 0.75, 0.5, 0.25]) {
      const cut = full.subarray(0, Math.floor(full.length * keep));
      try {
        decode(cut);
        decoded++;
      } catch (e) {
        expect(e).toBeInstanceOf(JpegUnsupportedError);
        refused++;
      }
    }
    // Every truncation must be refused. A decode that succeeds here returned a
    // model whose coefficients came partly from padding.
    expect(decoded, `${decoded} truncated files decoded instead of being refused`).toBe(0);
    expect(refused).toBe(5);
  });

  it('still accepts an untruncated file, so the bound is not merely strict', () => {
    // The other half: a bound that refused everything would satisfy the test
    // above while breaking every real file.
    expect(() => decode(makeJpeg(64, 64, 88, 11))).not.toThrow();
  });
});
