/**
 * Build the golden corpus: encoded artifacts that current decoders must keep
 * reading, forever, until a format version constant says otherwise.
 *
 * Why this exists, and why the existing fixtures are not it. Everything in
 * `python/tests/_fixtures` is gitignored and regenerated by the TypeScript
 * encoder on every CI run, so the encoder and the decoders can drift together
 * without a single test noticing. That is not hypothetical: it was demonstrated
 * twice on this repository. Changing the Galois field polynomial to 0x12D left
 * all 620 tests green, and switching the Cauchy assignment to ISA-L's left 48
 * encoder tests and all 93 Python decoder tests green. Both changed every byte
 * the encoder produces.
 *
 * `tests/vectors/crypto-vectors.json` is frozen and committed, but it pins the
 * crypto and blob layers only. Nothing pinned the stego carriers, the image
 * codecs, or the SQLite container.
 *
 * The rule that gives this corpus its value lives in `scripts/check-golden.ts`:
 * if a file here changes, a format version constant must change in the same
 * commit. That is what separates a deliberate format change, which bumps and
 * regenerates, from an accidental drift, where both stacks move together and
 * everything stays green.
 *
 * Run with: npm run golden
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'tests', 'golden');

/**
 * One artifact per output path, chosen for coverage rather than completeness.
 *
 * Gallery Mode is deliberately absent. Its smallest fixture is 2.4 MB against
 * about 1 MB for everything below put together, and committing it would grow the
 * repository by more than the corpus is worth. Its slot format is partially
 * pinned by the multiRegionSegmentedBlob vectors in crypto-vectors.json. Partial
 * is the honest word: the photo carriers themselves are not pinned, and that is
 * the one output path this corpus does not cover.
 */
const SETS = [
  ['embedded', 'QR-grid images, key block embedded (SPEC §2.1, §5.1)'],
  ['color-grid', 'eight-colour grid images (SPEC §2.2)'],
  ['keyfile', 'QR-grid images with a separate .key file (SPEC §5.2)'],
  ['stego', 'key block hidden in a PNG cover by spatial LSB (SPEC §5.3)'],
  ['stego-jpeg', 'key block hidden in a JPEG cover by DCT coefficient (SPEC §5.4)'],
  ['binary-branded', 'branded .ssbn container (SPEC §8)'],
  ['binary-disguised', 'disguised SQLite .db container (SPEC §8)'],
] as const;

function versionConstants(): Record<string, number> {
  const read = (file: string, name: string): number => {
    const src = readFileSync(join(ROOT, 'src', 'core', file), 'utf-8');
    const m = new RegExp(`${name}\\s*=\\s*(\\d+)`).exec(src);
    if (!m) throw new Error(`could not read ${name} from ${file}`);
    return Number(m[1]);
  };
  return {
    FORMAT_VERSION: read('header.ts', 'FORMAT_VERSION'),
    KEY_BLOCK_VERSION: read('crypto.ts', 'KEY_BLOCK_VERSION'),
    BINARY_VERSION: read('binary-container.ts', 'BINARY_VERSION'),
    CODEC_GALLERY: read('header.ts', 'CODEC_GALLERY'),
  };
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

function main(): void {
  const staging = mkdtempSync(join(tmpdir(), 'stegoshard-golden-'));
  try {
    // The corpus is a subset of the conformance fixtures, produced by the same
    // generator so there is one encoder path rather than two to keep in step.
    execFileSync(
      join(ROOT, 'node_modules', '.bin', 'tsx'),
      [join(ROOT, 'scripts', 'gen-fixtures.ts'), staging],
      { cwd: ROOT, stdio: 'inherit' },
    );

    rmSync(OUT, { recursive: true, force: true });
    mkdirSync(OUT, { recursive: true });
    for (const [name] of SETS) cpSync(join(staging, name), join(OUT, name), { recursive: true });

    const files = walk(OUT).sort();
    const digests = files.map((f) => {
      const rel = relative(OUT, f);
      const hash = createHash('sha256').update(readFileSync(f)).digest('hex');
      return `${hash}  ${rel}`;
    });
    const versions = versionConstants();
    const total = files.reduce((n, f) => n + statSync(f).size, 0);

    writeFileSync(
      join(OUT, 'PROVENANCE.md'),
      `# Golden corpus

Encoded artifacts that current decoders must keep reading. **Do not regenerate
these to make a test pass.** If a change makes them fail to decode, that is the
corpus doing its job.

Regenerating is legitimate exactly once per deliberate format change, and
\`scripts/check-golden.ts\` enforces the pairing: a diff here without a version
constant moving in the same commit fails CI.

    npm run golden

## What is pinned

${SETS.map(([n, why]) => `- \`${n}/\` — ${why}`).join('\n')}

Gallery Mode is not here. Its smallest fixture is 2.4 MB against about 1 MB for
everything above together. Its slot format is partially pinned by the
\`multiRegionSegmentedBlob\` vectors in \`tests/vectors/crypto-vectors.json\`;
the photo carriers themselves are not pinned at all. That is the one output path
this corpus leaves uncovered, and it is stated here rather than left to be
discovered.

## Format version constants at generation

${Object.entries(versions)
  .map(([k, v]) => `- \`${k}\` = ${v}`)
  .join('\n')}

## Contents

${files.length} files, ${(total / 1024).toFixed(0)} KiB.

\`\`\`
${digests.join('\n')}
\`\`\`
`,
    );
    console.log(`golden: ${files.length} files, ${(total / 1024).toFixed(0)} KiB -> tests/golden`);
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

main();
