"""Cross-implementation conformance: decode fixtures produced by the extension.

Fixtures are generated by `npm run fixtures -- python/tests/_fixtures` (the
extension's own core encodes and renders them). If these tests fail, the Python
decoder and the TypeScript encoder disagree on the format.
"""

from __future__ import annotations

import json
import pathlib

import pytest

from stegoshard import WrongPasswordError, decode_image, decode_vault
from stegoshard.pipeline import MissingKeyError

FIXTURES = pathlib.Path(__file__).parent / "_fixtures"

pytestmark = pytest.mark.skipif(
    not FIXTURES.exists(),
    reason="fixtures not generated (run: npm run fixtures -- python/tests/_fixtures)",
)


def _load(name: str):
    d = FIXTURES / name
    manifest = json.loads((d / "manifest.json").read_text())
    payloads = []
    for img in sorted(d.glob("page-*.png")):
        payload = decode_image(img.read_bytes())
        assert payload is not None, f"failed to decode {img.name}"
        payloads.append(payload)
    expected = (d / "expected.bin").read_bytes()
    key_path = d / "vault.key"
    key = key_path.read_bytes() if key_path.exists() else None
    return manifest, payloads, expected, key


def test_embedded_round_trip():
    manifest, payloads, expected, _key = _load("embedded")
    restored = decode_vault(payloads, manifest["password"])
    assert restored.filename == manifest["filename"]
    assert restored.content == expected


def test_keyfile_needs_external_key():
    manifest, payloads, expected, key = _load("keyfile")
    with pytest.raises(MissingKeyError):
        decode_vault(payloads, manifest["password"])
    restored = decode_vault(payloads, manifest["password"], key)
    assert restored.content == expected


def test_wrong_password_is_rejected():
    manifest, payloads, _expected, _key = _load("embedded")
    with pytest.raises(WrongPasswordError):
        decode_vault(payloads, "not the password")


def test_missing_image_is_tolerated():
    manifest, payloads, expected, _key = _load("embedded")
    # Drop one image; erasure coding still reconstructs (k data + m parity).
    restored = decode_vault(payloads[1:], manifest["password"])
    assert restored.content == expected


def test_stego_key_image_round_trip():
    """The key hidden in a cover photo is extracted with the password, then restores."""
    from stegoshard import extract_key_block_from_image

    d = FIXTURES / "stego"
    manifest = json.loads((d / "manifest.json").read_text())
    payloads = []
    for img in sorted(d.glob("page-*.png")):
        payload = decode_image(img.read_bytes())
        assert payload is not None
        payloads.append(payload)
    expected = (d / "expected.bin").read_bytes()

    # Without the key image, a stego set cannot be restored.
    with pytest.raises(MissingKeyError):
        decode_vault(payloads, manifest["password"])

    # A wrong password finds no key in the cover (indistinguishable from none).
    cover = (d / "key.png").read_bytes()
    assert extract_key_block_from_image(cover, "not the password") is None

    # The right password extracts the key block and restores the file.
    key_block = extract_key_block_from_image(cover, manifest["password"])
    assert key_block is not None
    restored = decode_vault(payloads, manifest["password"], key_block)
    assert restored.filename == manifest["filename"]
    assert restored.content == expected


def test_stego_jpeg_key_image_round_trip():
    """A key hidden in a baseline JPEG's DCT coefficients (TS embed) is extracted
    by the pure-Python coefficient reader and restores the file (SPEC §5.4)."""
    from stegoshard import extract_key_block_from_image

    d = FIXTURES / "stego-jpeg"
    manifest = json.loads((d / "manifest.json").read_text())
    payloads = []
    for img in sorted(d.glob("page-*.png")):
        payload = decode_image(img.read_bytes())
        assert payload is not None
        payloads.append(payload)
    expected = (d / "expected.bin").read_bytes()

    cover = (d / "key.jpg").read_bytes()
    assert cover[:2] == b"\xff\xd8"  # a real JPEG, not a PNG
    assert extract_key_block_from_image(cover, "not the password") is None

    key_block = extract_key_block_from_image(cover, manifest["password"])
    assert key_block is not None
    restored = decode_vault(payloads, manifest["password"], key_block)
    assert restored.filename == manifest["filename"]
    assert restored.content == expected


def test_binary_branded_round_trip():
    """A branded binary container (TS embed) restores via the reference decoder
    (SPEC §8)."""
    from stegoshard import decode_vault_binary, unwrap_binary

    d = FIXTURES / "binary-branded"
    manifest = json.loads((d / "manifest.json").read_text())
    container = (d / manifest["vault"]).read_bytes()
    expected = (d / "expected.bin").read_bytes()

    assert unwrap_binary(container)[1] == "branded"
    restored = decode_vault_binary(container, manifest["password"])
    assert restored.filename == manifest["filename"]
    assert restored.content == expected


def test_binary_disguised_needs_key_container():
    """A disguised (SQLite-header) vault plus its key container round-trips; the
    vault alone is rejected (SPEC §8)."""
    from stegoshard import decode_vault_binary, unwrap_binary
    from stegoshard.pipeline import MissingKeyError

    d = FIXTURES / "binary-disguised"
    manifest = json.loads((d / "manifest.json").read_text())
    container = (d / manifest["vault"]).read_bytes()
    expected = (d / "expected.bin").read_bytes()

    # The file carries a genuine SQLite header so file-type triage is fooled.
    assert container[:16] == b"SQLite format 3\x00"
    assert unwrap_binary(container)[1] == "disguised"

    with pytest.raises(MissingKeyError):
        decode_vault_binary(container, manifest["password"])

    key_container = (d / manifest["key"]).read_bytes()
    key_block = unwrap_binary(key_container)[0]
    restored = decode_vault_binary(container, manifest["password"], key_block)
    assert restored.content == expected
