"""The golden corpus: artifacts a current decoder must keep reading.

Every other test in this repository that decodes an image, a container or a
carrier decodes something the TypeScript encoder produced moments earlier in the
same CI run. `python/tests/_fixtures` is gitignored and regenerated on every run,
so the encoder and both decoders can drift together and stay green.

That is not a hypothetical. It was demonstrated twice on this repository:
changing the Galois field polynomial to 0x12D left all 620 TypeScript tests
green, and switching the Cauchy assignment to ISA-L's left 48 encoder tests and
all 93 Python decoder tests green. Both changed every byte the encoder writes.

`tests/golden/` is committed. These bytes were written once, by a known commit,
and are not regenerated by CI. If a change makes them stop decoding, the change
altered the format. `scripts/check-golden.ts` refuses a diff to the corpus that
does not come with a version constant bump in the same commit, which is what
separates a deliberate format change from an accidental drift.

The Python decoder is the right place for this. It is the independent
implementation; a corpus checked only by the encoder's own stack would prove
considerably less.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re

import pytest
from stegoshard import (
    WrongPasswordError,
    decode_any,
    decode_vault,
    decode_vault_binary,
)
from stegoshard.binary_container import unwrap_binary

GOLDEN = pathlib.Path(__file__).parents[2] / "tests" / "golden"

#: The corpus is committed, so unlike the generated fixtures there is no
#: legitimate reason for it to be missing.
#:
#: This used to be a `skipif`, directly under a comment saying a skip would hide
#: the drift the corpus exists to catch. It did exactly that: a deleted directory
#: reported ten skips and a zero exit. Collection now fails instead, here rather
#: than in conftest so the message names the corpus.
if not GOLDEN.exists():
    raise RuntimeError(
        f"the golden corpus is missing from {GOLDEN}. It is committed, so this "
        "means it was deleted rather than not yet generated. Skipping these tests "
        "would report green while nothing checked the wire format."
    )

IMAGE_SETS = ["embedded", "color-grid", "keyfile", "stego", "stego-jpeg"]
BINARY_SETS = ["binary-branded", "binary-disguised"]


def _manifest(name: str) -> dict:
    return json.loads((GOLDEN / name / "manifest.json").read_text())


def _expected(name: str) -> bytes:
    return (GOLDEN / name / "expected.bin").read_bytes()


@pytest.mark.parametrize("name", IMAGE_SETS)
def test_golden_images_still_decode(name: str) -> None:
    """Every committed image set restores its plaintext byte for byte."""
    d = GOLDEN / name
    manifest = _manifest(name)
    payloads = []
    for img in sorted(d.glob("page-*.png")):
        # No codec hint: decode_any picks from the pixels, as the apps do.
        payload = decode_any(img.read_bytes())
        assert payload is not None, f"{name}/{img.name} no longer decodes"
        payloads.append(payload)
    assert payloads, f"{name} has no page images"

    # The key block travels three ways, and each has to be reassembled the way a
    # user would: inside the images, in a .key file, or hidden in a cover photo
    # that only the password unlocks.
    key_block: bytes | None = None
    keyfile = d / "vault.key"
    cover = next((d / n for n in ("key.png", "key.jpg") if (d / n).exists()), None)
    if keyfile.exists():
        key_block = keyfile.read_bytes()
    elif cover is not None:
        from stegoshard import extract_key_block_from_image

        key_block = extract_key_block_from_image(cover.read_bytes(), manifest["password"])
        assert key_block is not None, f"{name}: the key block no longer extracts from its cover"

    restored = decode_vault(payloads, manifest["password"], key_block)
    assert restored.filename == manifest["filename"]
    assert restored.content == _expected(name)


@pytest.mark.parametrize("name", BINARY_SETS)
def test_golden_containers_still_restore(name: str) -> None:
    """The .ssbn and disguised .db paths, restored end to end.

    Unwrapping and checking the result is non-empty was the first version of this
    test, and it was too weak: a decoder returning a truncated or shifted payload
    would have passed while the committed container became unrecoverable, which is
    the one thing a golden corpus exists to prevent. The plaintext has to come
    back byte for byte, as it does for the image sets.
    """
    d = GOLDEN / name
    manifest = _manifest(name)
    container = (d / manifest["vault"]).read_bytes()

    payload, variant = unwrap_binary(container)
    assert variant == manifest["variant"]
    assert payload, f"{name} unwrapped to nothing"

    # A disguised .db is a multi-region container keyed by the password plus a
    # 32-byte factor carried in its companion file (SPEC §8, §10).
    key_factor = None
    if "key" in manifest:
        key_factor = unwrap_binary((d / manifest["key"]).read_bytes())[0]
        # Without the factor the slot KEK is wrong and nothing opens. Pinned
        # because a container that opened without it would mean the factor had
        # stopped gating anything.
        with pytest.raises(WrongPasswordError):
            decode_vault_binary(container, manifest["password"])

    restored = decode_vault_binary(container, manifest["password"], key_factor=key_factor)
    assert restored.filename == manifest["filename"]
    assert restored.content == _expected(name)


def test_corpus_covers_every_pinned_path() -> None:
    """The set cannot quietly shrink.

    A corpus that lost a directory would still pass every test above, because
    those are parametrised over the directories that exist. This asserts the list
    instead.
    """
    present = {p.name for p in GOLDEN.iterdir() if p.is_dir()}
    assert present == set(IMAGE_SETS) | set(BINARY_SETS), (
        f"golden corpus contents changed: {sorted(present)}. Adding a path is fine; "
        "update this list and PROVENANCE.md. Losing one is not."
    )


def test_every_file_in_provenance_is_present_and_unchanged() -> None:
    """Every digest recorded at generation still resolves.

    This is the guard that catches a missing *file*, which the directory check
    above does not. It earned its place immediately: `.gitignore` carries a
    blanket `*.key` rule, so `keyfile/vault.key` was silently left out of the
    commit. The suite passed locally, on the untracked file still sitting on
    disk, and failed only in a fresh CI checkout.
    """
    digests = []
    for line in (GOLDEN / "PROVENANCE.md").read_text().splitlines():
        m = re.match(r"^([0-9a-f]{64})  (.+)$", line)
        if m:
            digests.append((m.group(1), m.group(2)))
    assert len(digests) >= 40, f"PROVENANCE.md lists only {len(digests)} files"

    missing, altered = [], []
    for want, rel in digests:
        path = GOLDEN / rel
        if not path.exists():
            missing.append(rel)
            continue
        if hashlib.sha256(path.read_bytes()).hexdigest() != want:
            altered.append(rel)
    assert not missing, f"recorded but absent from the checkout: {missing}"
    assert not altered, f"present but no longer matching their recorded digest: {altered}"


def test_provenance_records_the_version_constants() -> None:
    """PROVENANCE.md carries the format constants the corpus was written under.

    Without them a future reader cannot tell whether a decode failure means the
    format moved deliberately or by accident.
    """
    text = (GOLDEN / "PROVENANCE.md").read_text()
    for constant in ("FORMAT_VERSION", "KEY_BLOCK_VERSION", "BINARY_VERSION", "CODEC_GALLERY"):
        assert constant in text, f"PROVENANCE.md does not record {constant}"
