"""The golden corpus: artifacts a current decoder must keep reading.

Every other test in this repository that decodes an image, a container or a
carrier decodes something the TypeScript encoder produced moments earlier in the
same CI run. `python/tests/_fixtures` is gitignored and regenerated on every run,
so the encoder and both decoders can drift together and stay green.

That is not a hypothetical. It was demonstrated twice on this repository:
changing the Galois field polynomial to 0x12D left all 620 TypeScript tests
green, and switching the Cauchy assignment to ISA-L's left 48 encoder tests and
all 93 Python decoder tests green. Both changed every byte the encoder writes.

`tests/golden/` is committed. These bytes were written once, by a known commit,
and are not regenerated by CI. If a change makes them stop decoding, the change
altered the format. `scripts/check-golden.ts` refuses a diff to the corpus that
does not come with a version constant bump in the same commit, which is what
separates a deliberate format change from an accidental drift.

The Python decoder is the right place for this. It is the independent
implementation; a corpus checked only by the encoder's own stack would prove
considerably less.
"""

from __future__ import annotations

import json
import pathlib

import pytest
from stegoshard import decode_any, decode_vault
from stegoshard.binary_container import unwrap_binary

GOLDEN = pathlib.Path(__file__).parents[2] / "tests" / "golden"

#: The corpus is committed, so unlike the generated fixtures there is no
#: legitimate reason for it to be missing. A skip here would hide exactly the
#: drift the corpus exists to catch.
pytestmark = pytest.mark.skipif(
    not GOLDEN.exists(), reason="tests/golden is missing from the checkout"
)

IMAGE_SETS = ["embedded", "color-grid", "keyfile", "stego", "stego-jpeg"]
BINARY_SETS = ["binary-branded", "binary-disguised"]


def _manifest(name: str) -> dict:
    return json.loads((GOLDEN / name / "manifest.json").read_text())


def _expected(name: str) -> bytes:
    return (GOLDEN / name / "expected.bin").read_bytes()


@pytest.mark.parametrize("name", IMAGE_SETS)
def test_golden_images_still_decode(name: str) -> None:
    """Every committed image set restores its plaintext byte for byte."""
    d = GOLDEN / name
    manifest = _manifest(name)
    payloads = []
    for img in sorted(d.glob("page-*.png")):
        # No codec hint: decode_any picks from the pixels, as the apps do.
        payload = decode_any(img.read_bytes())
        assert payload is not None, f"{name}/{img.name} no longer decodes"
        payloads.append(payload)
    assert payloads, f"{name} has no page images"

    # The key block travels three ways, and each has to be reassembled the way a
    # user would: inside the images, in a .key file, or hidden in a cover photo
    # that only the password unlocks.
    key_block: bytes | None = None
    keyfile = d / "vault.key"
    cover = next((d / n for n in ("key.png", "key.jpg") if (d / n).exists()), None)
    if keyfile.exists():
        key_block = keyfile.read_bytes()
    elif cover is not None:
        from stegoshard import extract_key_block_from_image

        key_block = extract_key_block_from_image(cover.read_bytes(), manifest["password"])
        assert key_block is not None, f"{name}: the key block no longer extracts from its cover"

    restored = decode_vault(payloads, manifest["password"], key_block)
    assert restored.filename == manifest["filename"]
    assert restored.content == _expected(name)


@pytest.mark.parametrize("name", BINARY_SETS)
def test_golden_containers_still_unwrap(name: str) -> None:
    """The .ssbn and disguised .db framings, which the frozen crypto vectors do
    not reach: those pin the vault blob, not the container around it."""
    manifest = _manifest(name)
    blob = (GOLDEN / name / manifest["vault"]).read_bytes()
    payload, variant = unwrap_binary(blob)
    assert variant == manifest["variant"]
    assert payload, f"{name} unwrapped to nothing"


def test_corpus_covers_every_pinned_path() -> None:
    """The set cannot quietly shrink.

    A corpus that lost a directory would still pass every test above, because
    those are parametrised over the directories that exist. This asserts the list
    instead.
    """
    present = {p.name for p in GOLDEN.iterdir() if p.is_dir()}
    assert present == set(IMAGE_SETS) | set(BINARY_SETS), (
        f"golden corpus contents changed: {sorted(present)}. Adding a path is fine; "
        "update this list and PROVENANCE.md. Losing one is not."
    )


def test_provenance_records_the_version_constants() -> None:
    """PROVENANCE.md carries the format constants the corpus was written under.

    Without them a future reader cannot tell whether a decode failure means the
    format moved deliberately or by accident.
    """
    text = (GOLDEN / "PROVENANCE.md").read_text()
    for constant in ("FORMAT_VERSION", "KEY_BLOCK_VERSION", "BINARY_VERSION", "CODEC_GALLERY"):
        assert constant in text, f"PROVENANCE.md does not record {constant}"
