"""Cross-implementation known-answer tests against tests/vectors/crypto-vectors.json.

The vectors were generated by the TypeScript stack (hash-wasm Argon2id +
WebCrypto AES-GCM) from fixed inputs. This suite reproduces every output with
fully independent implementations — argon2-cffi (binding the official
phc-winner-argon2 C code) and `cryptography` (OpenSSL) — proving both stacks
agree bit-for-bit on Argon2id, AES-256-GCM, the key block, and the vault blob.

Two authoritative AES-256-GCM test cases from the original GCM specification
are also checked, so the platform itself is validated against a third party
rather than only the two implementations agreeing with each other.
"""

from __future__ import annotations

import json
import pathlib
import unicodedata

import pytest
from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from imagevault.crypto import WrongPasswordError, decrypt_content, derive_kek, unwrap_dek
from imagevault.format import parse_envelope, parse_key_block, parse_vault_blob

VECTORS_PATH = pathlib.Path(__file__).parents[2] / "tests" / "vectors" / "crypto-vectors.json"
VECTORS = json.loads(VECTORS_PATH.read_text(encoding="utf-8"))


def _hx(s: str) -> bytes:
    return bytes.fromhex(s)


# ---- Argon2id KEK derivation --------------------------------------------------


@pytest.mark.parametrize("v", VECTORS["argon2id"], ids=lambda v: v["name"])
def test_argon2id_kek_matches_typescript(v):
    kek = derive_kek(v["password"], _hx(v["saltHex"]), v["iterations"], v["memoryKiB"], v["parallelism"])
    assert kek == _hx(v["kekHex"])


def test_nfc_and_nfd_passwords_derive_same_kek():
    """Passwords are NFC-normalized before hashing; both stacks must agree."""
    nfc = next(v for v in VECTORS["argon2id"] if v["name"] == "unicode-nfc")
    nfd = next(v for v in VECTORS["argon2id"] if v["name"] == "unicode-nfd")
    # Different raw bytes, same normalized text -> identical KEK.
    assert nfc["password"] != nfd["password"]
    assert unicodedata.normalize("NFC", nfc["password"]) == unicodedata.normalize("NFC", nfd["password"])
    assert nfc["kekHex"] == nfd["kekHex"]
    # And derive_kek reproduces that shared KEK from either spelling.
    kek_from_nfd = derive_kek(
        nfd["password"], _hx(nfd["saltHex"]), nfd["iterations"], nfd["memoryKiB"], nfd["parallelism"]
    )
    assert kek_from_nfd == _hx(nfc["kekHex"])


# ---- AES-256-GCM ---------------------------------------------------------------


@pytest.mark.parametrize("v", VECTORS["aesGcm"], ids=lambda v: v["name"])
def test_aes_gcm_matches_typescript(v):
    aead = AESGCM(_hx(v["keyHex"]))
    assert aead.encrypt(_hx(v["ivHex"]), _hx(v["plaintextHex"]), None) == _hx(v["ciphertextHex"])
    assert aead.decrypt(_hx(v["ivHex"]), _hx(v["ciphertextHex"]), None) == _hx(v["plaintextHex"])


@pytest.mark.parametrize("v", VECTORS["aesGcm"], ids=lambda v: v["name"])
def test_aes_gcm_rejects_any_flipped_bit(v):
    aead = AESGCM(_hx(v["keyHex"]))
    ct = bytearray(_hx(v["ciphertextHex"]))
    for i in range(len(ct)):
        mutated = bytearray(ct)
        mutated[i] ^= 0x01
        with pytest.raises(InvalidTag):
            aead.decrypt(_hx(v["ivHex"]), bytes(mutated), None)


def test_authoritative_gcm_spec_vectors():
    aead = AESGCM(b"\x00" * 32)
    iv = b"\x00" * 12
    assert aead.encrypt(iv, b"", None) == _hx("530f8afbc74536b9a963b4f1c4cb738b")
    assert aead.encrypt(iv, b"\x00" * 16, None) == _hx(
        "cea7403d4d606b6e074ec5d3baf39d18d0d1c8a799996bf0265b98b5d48ab919"
    )


# ---- Full key block --------------------------------------------------------------


@pytest.mark.parametrize("v", VECTORS["keyBlock"], ids=lambda v: v["name"])
def test_key_block_unwraps_to_exact_dek(v):
    block = parse_key_block(_hx(v["blockHex"]))
    assert unwrap_dek(block, v["password"]) == _hx(v["dekHex"])


@pytest.mark.parametrize("v", VECTORS["keyBlock"], ids=lambda v: v["name"])
def test_key_block_rejects_wrong_password(v):
    block = parse_key_block(_hx(v["blockHex"]))
    with pytest.raises(WrongPasswordError):
        unwrap_dek(block, v["password"] + "x")


def test_key_block_rejects_wrapped_dek_corruption():
    v = VECTORS["keyBlock"][0]
    raw = bytearray(_hx(v["blockHex"]))
    # Corrupt each byte of the wrapped DEK region (offset 44 onward).
    for i in range(44, len(raw)):
        mutated = bytearray(raw)
        mutated[i] ^= 0x80
        with pytest.raises(WrongPasswordError):
            unwrap_dek(parse_key_block(bytes(mutated)), v["password"])


def test_key_block_rejects_trailing_bytes():
    v = VECTORS["keyBlock"][0]
    with pytest.raises(ValueError, match="trailing"):
        parse_key_block(_hx(v["blockHex"]) + b"\x00")


# ---- Full vault blob ---------------------------------------------------------------


@pytest.mark.parametrize("v", VECTORS["vaultBlob"], ids=lambda v: v["name"])
def test_vault_blob_decrypts_to_expected_content(v):
    key_block_bytes, iv, ciphertext = parse_vault_blob(_hx(v["blobHex"]))
    if v["mode"] == "keyfile":
        assert key_block_bytes == b""
        key_block_bytes = _hx(v["keyBlockHex"])
    else:
        assert key_block_bytes == _hx(v["keyBlockHex"])

    dek = unwrap_dek(parse_key_block(key_block_bytes), v["password"])
    filename, content = parse_envelope(decrypt_content(dek, iv, ciphertext))
    assert filename == v["filename"]
    assert content == _hx(v["contentHex"])
