"""Cross-implementation conformance: decode fixtures produced by the extension.

Fixtures are generated by `npm run fixtures -- python/tests/_fixtures` (the
extension's own core encodes and renders them). If these tests fail, the Python
decoder and the TypeScript encoder disagree on the format.
"""

from __future__ import annotations

import json
import pathlib

import pytest

from imagevault import WrongPasswordError, decode_image, decode_vault
from imagevault.pipeline import MissingKeyError

FIXTURES = pathlib.Path(__file__).parent / "_fixtures"

pytestmark = pytest.mark.skipif(
    not FIXTURES.exists(),
    reason="fixtures not generated (run: npm run fixtures -- python/tests/_fixtures)",
)


def _load(name: str):
    d = FIXTURES / name
    manifest = json.loads((d / "manifest.json").read_text())
    payloads = []
    for img in sorted(d.glob("page-*.png")):
        payload = decode_image(img.read_bytes())
        assert payload is not None, f"failed to decode {img.name}"
        payloads.append(payload)
    expected = (d / "expected.bin").read_bytes()
    key_path = d / "vault.key"
    key = key_path.read_bytes() if key_path.exists() else None
    return manifest, payloads, expected, key


def test_embedded_round_trip():
    manifest, payloads, expected, _key = _load("embedded")
    restored = decode_vault(payloads, manifest["password"])
    assert restored.filename == manifest["filename"]
    assert restored.content == expected


def test_keyfile_needs_external_key():
    manifest, payloads, expected, key = _load("keyfile")
    with pytest.raises(MissingKeyError):
        decode_vault(payloads, manifest["password"])
    restored = decode_vault(payloads, manifest["password"], key)
    assert restored.content == expected


def test_wrong_password_is_rejected():
    manifest, payloads, _expected, _key = _load("embedded")
    with pytest.raises(WrongPasswordError):
        decode_vault(payloads, "not the password")


def test_missing_image_is_tolerated():
    manifest, payloads, expected, _key = _load("embedded")
    # Drop one image; erasure coding still reconstructs (k data + m parity).
    restored = decode_vault(payloads[1:], manifest["password"])
    assert restored.content == expected


def test_stego_key_image_round_trip():
    """The key hidden in a cover photo is extracted with the password, then restores."""
    from imagevault import extract_key_block_from_image

    d = FIXTURES / "stego"
    manifest = json.loads((d / "manifest.json").read_text())
    payloads = []
    for img in sorted(d.glob("page-*.png")):
        payload = decode_image(img.read_bytes())
        assert payload is not None
        payloads.append(payload)
    expected = (d / "expected.bin").read_bytes()

    # Without the key image, a stego set cannot be restored.
    with pytest.raises(MissingKeyError):
        decode_vault(payloads, manifest["password"])

    # A wrong password finds no key in the cover (indistinguishable from none).
    cover = (d / "key.png").read_bytes()
    assert extract_key_block_from_image(cover, "not the password") is None

    # The right password extracts the key block and restores the file.
    key_block = extract_key_block_from_image(cover, manifest["password"])
    assert key_block is not None
    restored = decode_vault(payloads, manifest["password"], key_block)
    assert restored.filename == manifest["filename"]
    assert restored.content == expected
